### ISSUE TITLE
NetBox 3.2 Support

### ISSUE THREAD

**Issue by ryanmerolle** [sanecz/netbox-ipmi-ovh-plugin#2]
[NetBox 3.2.0](https://github.com/netbox-community/netbox/releases/tag/v3.2.0) was just released and has a number of [extension improvements](https://github.com/netbox-community/netbox/issues/8333).

Furthermore, a [NetBox 3.2 plugin tutorial](https://github.com/netbox-community/netbox-plugin-tutorial) was released

**Comment by sanecz** [comment]
Hi,

Thanks for the update, i'll see for the support of netbox 3.2.

Thanks!

**Comment by quiknick** [comment]
Bumping the issue. Hope @sanecz can fix this. Thanks in advance!

**Comment by sanecz** [comment]
Hi,
I have tested the plugin with Netbox v3.2.2 and everything seems to work without any issues.

On the code side, no impact with the new features
